# -*- coding: utf-8 -*-
"""projectStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvPd0wo6MmsN9ENdNkdc07ffT3pRwKBd
"""

import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import sqlite3

st.set_page_config(page_title="High-Income Careers Analysis", layout="wide")

# -----------------------------
# LOAD DATA
# -----------------------------
@st.cache_data
def load_data():
    ipums = pd.read_csv('IPUMS.csv')
    ipums['TELWRKPAY'] = ipums['TELWRKPAY'].fillna(0)

    occ = pd.read_csv('Occupation_Codes.csv')
    occ['OCC Code'] = occ['OCC Code'].replace('000N', '0').astype(int)

    conn = sqlite3.connect(':memory:')
    ipums.to_sql('ip', conn, index=False, if_exists='replace')
    occ.to_sql('oc', conn, index=False, if_exists='replace')

    df = pd.read_sql("""
        SELECT ip.*, oc."Occupation Title", oc."Major Category"
        FROM ip
        LEFT JOIN oc ON ip.OCC = oc."OCC Code"
    """, conn)
    conn.close()

    df = df[
        (df['AGE'].between(18, 35)) &
        (df['UHRSWORKT'].between(26, 59)) &
        (df['INCWAGE'].between(75000, 200000)) &
        (df['OCC'] != 0)
    ].copy()

    return df

df = load_data()

# TITLE
st.title("💼 High-Income Entry Careers: Pay vs Time Commitment")

st.markdown("""
This app explores **which careers pay well early in life** and  
**how many hours you must work to earn that income**.
""")


# WIDGET
threshold = st.slider(
    "Define 'High Income'",
    75000, 200000, 120000, step=5000
)

df['HighIncome'] = df['INCWAGE'] >= threshold


# FILTER TO HIGH INCOME CAREERS
high_df = df[df['HighIncome']]


# PLOT 1: Top careers to pay
st.subheader("Which Careers Pay the Most Early?")

top_careers = (
    high_df.groupby('Major Category')['INCWAGE']
    .mean()
    .sort_values(ascending=False)
    .head(8)
    .reset_index()
)

fig1 = px.bar(
    top_careers,
    x='Major Category',
    y='INCWAGE',
    text_auto=True,
    title="Top Paying Career Categories (Ages 18–35)"
)

fig1.update_layout(xaxis_title="Career Category", yaxis_title="Average Income ($)")

st.plotly_chart(fig1, use_container_width=True)

# PLOT 2: Hours required
st.subheader("⏱️ How Many Hours Do These Careers Require?")

hours_by_career = (
    high_df.groupby('Major Category')['UHRSWORKT']
    .mean()
    .sort_values(ascending=False)
    .loc[top_careers['Major Category']]
    .reset_index()
)

fig2 = px.bar(
    hours_by_career,
    x='Major Category',
    y='UHRSWORKT',
    text_auto=True,
    title="Average Weekly Hours for High-Income Careers"
)

fig2.update_layout(xaxis_title="Career Category", yaxis_title="Hours per Week")

st.plotly_chart(fig2, use_container_width=True)

# Key Insight
st.subheader(" Key Insight")

st.write(f"""
At a ${threshold:,}+ income level:

- Some careers achieve high pay **without extreme hours**
- Others require **longer work weeks to reach similar income**

 This shows that **career choice impacts both income AND lifestyle**,  
not just how hard or long you work.
""")

# Optional Data View
with st.expander("📄 View Data"):
    st.dataframe(df.head())
