# -*- coding: utf-8 -*-
"""projectStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvPd0wo6MmsN9ENdNkdc07ffT3pRwKBd
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
import plotly.express as px
import sqlite3

# Function to load and preprocess data
@st.cache_data
def load_data():
    # Load IPMUS data
    IPMUS_df = pd.read_csv('IPUMS.csv')

    # Handle missing values for TELWRKPAY
    IPMUS_df['TELWRKPAY'] = IPMUS_df['TELWRKPAY'].fillna(0)

    # Load occupation codes
    occupation_codes_df = pd.read_csv('Occupation_Codes.csv')
    occupation_codes_df['OCC Code'] = occupation_codes_df['OCC Code'].replace('000N', '0')
    occupation_codes_df['OCC Code'] = occupation_codes_df['OCC Code'].astype(int)

    # Create a temporary SQLite database to merge dataframes
    conn = sqlite3.connect(':memory:')
    IPMUS_df.to_sql('IPMUS_df', conn, if_exists='replace', index=False)
    occupation_codes_df.to_sql('occupation_codes_df', conn, if_exists='replace', index=False)

    merged_df = pd.read_sql_query(
        """
        SELECT
            ip.*,
            oc."Occupation Title",
            oc."Major Category"
        FROM
            IPMUS_df ip
        LEFT JOIN
            occupation_codes_df oc ON ip.OCC = oc."OCC Code"
        """,
        conn
    )
    conn.close()

    # Filter data
    filtered_df = merged_df[
        (merged_df['AGE'] >= 18) & (merged_df['AGE'] <= 35) &
        (merged_df['UHRSWORKT'] < 60) & (merged_df['UHRSWORKT'] > 25) &
        (merged_df['INCWAGE'] < 200000) & (merged_df['INCWAGE'] > 75000) &
        (merged_df['OCC'] != 0)
    ].copy()

    # Create new variables
    filtered_df['HighEarner'] = (filtered_df['INCWAGE'] > filtered_df['INCWAGE'].median()).astype(int)
    filtered_df['HourlyEfficiency'] = filtered_df['INCWAGE'] / (filtered_df['WKSWORK1'] * filtered_df['UHRSWORKT'])
    filtered_df['EdWorkIntensity'] = filtered_df['EDUC'] * filtered_df['UHRSWORKT']

    # Drop 'STATEFIP' as it was identified as a noise variable
    filtered_df = filtered_df.drop(columns=['STATEFIP'], errors='ignore')

    return filtered_df

# Load data
df = load_data()

# Streamlit App Title
st.title('Career Earnings and Work-Life Analysis')

# Section: Income Distribution - Boxplot
st.header('Income Distribution - Boxplot')
fig_boxplot = px.box(df, y="INCWAGE", title="Income Boxplot")
st.plotly_chart(fig_boxplot)

# Section: Income Distribution - Histogram
st.header('Income Distribution - Histogram')
fig_hist = px.histogram(df, x="INCWAGE", nbins=50, title="Income Histogram")
st.plotly_chart(fig_hist)

# Section: Average Income by Occupation
st.header('Average Income by Occupation')
avg_income_by_occ = df.groupby('Occupation Title')['INCWAGE'].mean().sort_values(ascending=False).reset_index()
fig_avg_income_occ = px.bar(
    avg_income_by_occ,
    x='Occupation Title',
    y='INCWAGE',
    title='Average Annual Income by Occupation',
    labels={'INCWAGE': 'Average Annual Income ($)', 'Occupation Title': 'Occupation'},
    height=600 # Adjust height for better readability of many bars
)
st.plotly_chart(fig_avg_income_occ)

st.write('Explore income, work hours, and hourly efficiency for young professionals (18-35 years old) earning between $75,000 and $200,000, working 26-59 hours a week.')

# Display overall statistics (keeping this as general context, not a graph)
st.header('Overall Statistics')
st.write(f"Total individuals analyzed: {len(df)}")
st.write(f"Average Annual Income: ${df['INCWAGE'].mean():,.2f}")
st.write(f"Average Hours Worked Per Week: {df['UHRSWORKT'].mean():.2f}")
st.write(f"Average Hourly Efficiency: ${df['HourlyEfficiency'].mean():,.2f}")
